//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureCognitiveServices.Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class AzureCognitiveServicesTestsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AzureCognitiveServicesTestsSettings defaultInstance = ((AzureCognitiveServicesTestsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AzureCognitiveServicesTestsSettings())));
        
        public static AzureCognitiveServicesTestsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://???.cognitiveservices.azure.com")]
        public string AzureVisionFaceEndPoint {
            get {
                return ((string)(this["AzureVisionFaceEndPoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("???")]
        public string AzureVisionFaceApiKey {
            get {
                return ((string)(this["AzureVisionFaceApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("recognition_04")]
        public string AzureVisionFaceRecognitionModel {
            get {
                return ((string)(this["AzureVisionFaceRecognitionModel"]));
            }
        }
    }
}
